EduHome/ViewComponents/FooterViewComponent.cs
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private AppDbContext _context;
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio bio = _context.Bios.FirstOrDefault();
            return View(await Task.FromResult(bio));

        }
    }
}

EduHome/ViewComponents/HeaderViewComponent.cs
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private AppDbContext _context;
        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Bio bio = _context.Bios.FirstOrDefault();
            return View(await Task.FromResult(bio));
        }
    }
}

EduHome/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">
    
<!-- Mirrored from demo.devitems.com/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:44:02 GMT -->
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Eduhome - Educational HTML Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="~/image/apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="~/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/animate.css">
        <link rel="stylesheet" href="~/css/meanmenu.css">
        <link rel="stylesheet" href="~/css/magnific-popup.css">
        <link rel="stylesheet" href="~/css/owl.carousel.min.css">
        <link rel="stylesheet" href="~/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/et-line-icon.css">
        <link rel="stylesheet" href="~/css/reset.css">
        <link rel="stylesheet" href="~/css/ionicons.min.css">
        <link rel="stylesheet" href="~/css/material-design-iconic-font.min.css">
        <link rel="stylesheet" href="~/css/style.css">
        <link rel="stylesheet" href="~/css/responsive.css">
        <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        @await Component.InvokeAsync("Header")
        @RenderBody()
       @await Component.InvokeAsync("Footer")
        <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/jquery.meanmenu.js"></script>
        <script src="~/js/jquery.magnific-popup.js"></script>
        <script src="~/js/ajax-mail.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/jquery.mb.YTPlayer.js"></script>
        <script src="~/js/jquery.nicescroll.min.js"></script>
        <script src="~/js/plugins.js"></script>
        <script src="~/js/main.js"></script>
    </body>

<!-- Mirrored from demo.devitems.com/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:44:03 GMT -->
</html>