EduHome/Models/NoticeRightInfo.cs
namespace EduHome.Models
{
    public class NoticeRightInfo
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public string Description { get; set; }
    }
}

EduHome/Areas/AdminF/Controllers/NoticeRightInfoController.cs
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.Areas.AdminF.Controllers
{
    [Area("Adminf")]
    public class NoticeRightInfoController : Controller
    {
        private AppDbContext _context;
        public NoticeRightInfoController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            List<NoticeRightInfo> noticeRightInfos = _context.NoticeRightInfos.ToList();

            return View(noticeRightInfos);
            
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return NotFound();
            NoticeRightInfo dbnoticeRightInfo = await _context.NoticeRightInfos.FindAsync(id);
            if (dbnoticeRightInfo == null) return NotFound();
            return View(dbnoticeRightInfo);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            NoticeRightInfo dbnoticeRightInfo = await _context.NoticeRightInfos.FindAsync(id);
            if (dbnoticeRightInfo == null) return NotFound();
            _context.NoticeRightInfos.Remove(dbnoticeRightInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(NoticeRightInfo noticeRightInfo)
        {
            if (ModelState.IsValid)
            {
                return View();
            }

            return Content($"{noticeRightInfo.Title} {noticeRightInfo.Description}");
        }
    }
}

EduHome/Areas/AdminF/Views/NoticeRightInfo/Create.cshtml
@model NoticeRightInfo
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="row">
         <form method="post" class="forms-sample">
                    <div class="form-group">
                      <label asp-for="Title"></label>
                      <input asp-for="Title" type="text" class="form-control" placeholder="Title">
                      <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                      <div class="form-group">
                      <label asp-for="Description"></label>
                      <input asp-for="Description" type="text" class="form-control" placeholder="desc">
                      <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                  </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation"/>
}

EduHome/Areas/AdminF/Views/NoticeRightInfo/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}

<h1>@Model.Title</h1>
<p>@Model.Description</p>
<a asp-controller="NoticeRightInfo" asp-action="Index" class="btn btn-dark">Back</a>

<a asp-controller="NoticeRightInfo" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-dark">Delete</a>

EduHome/Areas/AdminF/Views/NoticeRightInfo/Detail.cshtml
@model NoticeRightInfo
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}
<h1>@Model.Title</h1>
<p>@Model.Description</p>
<a asp-controller="NoticeRightInfo" asp-action="Index" class="btn btn-dark">Back</a>

EduHome/Areas/AdminF/Views/NoticeRightInfo/Index.cshtml
@model IEnumerable<NoticeRightInfo>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}

<div class="row">
            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">NoticeRightInfo Table</h4>
                  <a class="btn btn-success" asp-controller="NoticeRightInfo" asp-action="Create">Create</a>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Count</th>
                          <th>Title</th>
                          <th>Setting</th>
                        </tr>
                      </thead>
                      <tbody>
                       @foreach (var item in Model)
                            {
                                count++;
                                <tr>
                          <td>@count</td>
                          <td>@item.Title</td>
                          <td>
                              <a class="btn btn-danger" asp-controller="NoticeRightInfo" asp-action="Delete" asp-route-id="@item.Id"><i class="mdi mdi-delete"><i/></a><br>
                              <a class="btn btn-primary" asp-controller="NoticeRightInfo" asp-action="Update" asp-route-id="@item.Id"><i class="mdi mdi-table-edit"><i/></a><br>
                              <a class="btn btn-info" asp-controller="NoticeRightInfo" asp-action="Detail" asp-route-id="@item.Id"><i class="mdi mdi-account-card-details"><i/></a><br>
                          </td>
                        </tr>
                      }
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            </div>